### ISSUE TITLE
Island Fly turns off when leaving the server.

### ISSUE THREAD

**Issue by MamaBeau** [BentoBoxWorld/IslandFly#33]
Hello, when players on my server that have the island fly permission are flying on their island, leave the server or the server restarts, their fly is toggled off causing them to fall and die. 
Also an issue I see, and feature that could be added along to this, is making island fly stay on for ever, even when the player leaves their island and comes back.

#### Steps to reproduce the behavior
Log into a server using the Island Fly addon, join and island and do /is fly log out, log back in.

#### Expected behavior
In the description of Island Fly it states there is a config choice to have island fly turned off when a player leaves the server. In my config it is set to False. I believe this feature is glitched, and that the island fly should remain on everytime the player leaves the server or the server is closed.

#### Screenshots and videos (Optional)
None to present at this time. More than welcome to join and test.

##### BentoBox Version (Mandatory)
1.11.1

#### Plugins (Optional)

```
Plugins (53): AntiWorldFly, BentoBox, BetterRTP*, BlockVersion*, BuycraftX, ChatColor.lua, ChatControl, ChatReaction, ChestCommands, Citizens, Clear
 EpicRename, Essentials, EssentialsSpawn, FeatherBoard*, FogusCore, GodsEye, GoldenCrates, HolographicDisplays, HolographicExtension*, InfiniteAnnouncements, ItemJoi
ore, Multiverse-NetherPortals, MVdWPlaceholderAPI*, NametagEdit*, NoGodDamnVillagerTrading, PlaceholderAPI, PlugMan, ProtocolLib, ProtocolSupport, ShopGUIPlus, SkyCr
b, TitleManager, Vault, VoteParty, Votifier, WorldEdit, WorldGuard
```
 
### Additional context (Optional)
Not at this time, thank you.

**Comment by tastybento** [comment]
This is confirmed. The server clears the fly and fly allowed states when the player logs in. 

Fixing it looks like it'll need some work: We'll need to save the fly state of the user when they log off and then put it back when they log on.

**Comment by MamaBeau** [comment]
Anyway that while doing so, we can add support for them to keep their fly when leaving the island to go to another part of the server?

**Comment by MamaBeau** [comment]
Will I be notified when this is complete?

**Comment by tastybento** [comment]
This issue is fixed and I just did a release. For the other feature you wanted, file another request and add some more explanation because I don't understand what you want there exactly.

**Comment by MamaBeau** [comment]
Sorry to due this to ya Bento, but It's still not working with the latest update.

**Comment by tastybento** [comment]
@MamaBeau It works. You have to be at least 2 air blocks high for fly to auto turn on. Config also has to be set to not disable fly on logout.

Here is the sequence I use for testing:

1. Do /island to make sure you are on your island
2. Do /is fly to turn on fly
3. Fly up so I'm at least 2 blocks up in the air
4. Log out
5. Log in - you'll see a message saying your fly mode has been enabled.

If you run that sequence and don't see that happen, then let me know.

**Comment by MamaBeau** [comment]
I've done those steps. It is indeed working. Thank you Bento, sorry for your time.
